In [2]:
import torch

In [10]:
a = torch.rand(2,3)
a

tensor([[0.1464, 0.7134, 0.2740],
        [0.2042, 0.1410, 0.3488]])

In [11]:
torch.tensor([[2],[3]]) + a

tensor([[2.1464, 2.7134, 2.2740],
        [3.2042, 3.1410, 3.3488]])

In [13]:
torch.cuda.is_available()

False

In [14]:
import torch.nn as nn
import torch.nn.functional as f


In [15]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        x = f.max_pool2d(f.relu(self.conv1(x)),(2,2))
        
        x = f.max_pool2d(f.relu(self.conv2(x)),2)
        x = x.view(-1, self.num_flat_features(x))
        x = f.relu(self.fc1(x))
        x = f.relu(self.fc2(x))
        
        x = self.fc3(x)
        return x

In [16]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [18]:
target = torch.rand(10)
target

tensor([0.1756, 0.3251, 0.9794, 0.1546, 0.5191, 0.6347, 0.4364, 0.1055, 0.6940,
        0.6472])

In [20]:
target.reshape(1,-1)

tensor([[0.1756, 0.3251, 0.9794, 0.1546, 0.5191, 0.6347, 0.4364, 0.1055, 0.6940,
         0.6472]])

# CIFAR10


In [21]:
import torch
import torchvision
import torchvision.transforms as transforms

In [24]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

# trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
#                                         download=True, transform=transform)
# trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
#                                           shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

KeyboardInterrupt: 

In [23]:
trainset

NameError: name 'trainset' is not defined

In [35]:
a = torch.tensor([[2,3,4],[2,3,4]])

In [40]:
torch.tensor(a.size()).prod()

tensor(6)